# Generated by Django 5.1.1 on 2024-09-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_name",
                    models.CharField(db_index=True, max_length=250, unique=True),
                ),
                (
                    "property_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("rural", "Rural"),
                            ("land", "Land"),
                            ("rental", "Rental"),
                            ("other", "Other"),
                        ],
                        max_length=250,
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "accessibility",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("total_room_number", models.PositiveIntegerField()),
                ("available", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer",
                    models.CharField(db_index=True, max_length=250, unique=True),
                ),
                ("room_number", models.PositiveIntegerField()),
                ("reservation_date", models.DateTimeField(auto_now_add=True)),
                ("reservation_starts", models.DateField()),
                ("reservation_ends", models.DateField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="contracts.property",
                    ),
                ),
            ],
        ),
    ]
