# Generated by Django 5.1.1 on 2024-09-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="available",
        ),
        migrations.AddField(
            model_name="property",
            name="reserved_rooms_number",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                    ("rural", "Rural"),
                    ("land", "Land"),
                    ("rental", "Rental"),
                    ("other", "Other"),
                ],
                default="rental",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="total_room_number",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
