# Generated by Django 5.1.1 on 2024-09-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_remove_property_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="customer",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_ends",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_starts",
            field=models.DateTimeField(),
        ),
    ]
