# Generated by Django 5.1.1 on 2024-09-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_alter_reservation_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="reserved_rooms_number",
        ),
    ]
